import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';
import sitemap from '@astrojs/sitemap';

export default defineConfig({
  site: 'https://leadpaintprofessionals.com',
  integrations: [
    tailwind(),
    sitemap()
  ],
  output: 'static',
  redirects: {
    '/services/portland/chemical-lead-paint-removal': '/services/portland/lead-paint-removal-surface-preparation',
    '/services/seattle/chemical-lead-paint-removal':  '/services/seattle/lead-paint-removal-surface-preparation',
    '/services/portland/chemical-lead-paint-stripping': '/services/portland/lead-paint-removal-surface-preparation',
    '/services/seattle/chemical-lead-paint-stripping':  '/services/seattle/lead-paint-removal-surface-preparation',
    '/services/portland/heat-gun-lead-paint-removal': '/services/portland/lead-paint-removal-surface-preparation',
    '/services/seattle/heat-gun-lead-paint-removal':  '/services/seattle/lead-paint-removal-surface-preparation',
    '/services/portland/lead-dust-cleanup-services': '/services/portland/lead-paint-containment-cleanup',
    '/services/seattle/lead-dust-cleanup-services':  '/services/seattle/lead-paint-containment-cleanup',
    '/services/portland/lead-hazard-control-consultation': '/services/portland/lead-paint-testing-inspection',
    '/services/seattle/lead-hazard-control-consultation':  '/services/seattle/lead-paint-testing-inspection',
    '/services/portland/lead-paint-abatement-services': '/services/portland/lead-paint-removal-surface-preparation',
    '/services/seattle/lead-paint-abatement-services':  '/services/seattle/lead-paint-removal-surface-preparation',
    '/services/portland/lead-paint-compliance-inspections': '/services/portland/lead-paint-testing-inspection',
    '/services/seattle/lead-paint-compliance-inspections':  '/services/seattle/lead-paint-testing-inspection',
    '/services/portland/lead-paint-encapsulation': '/services/portland/lead-paint-stabilization-encapsulation',
    '/services/seattle/lead-paint-encapsulation':  '/services/seattle/lead-paint-stabilization-encapsulation',
    '/services/portland/lead-paint-encapsulation-services': '/services/portland/lead-paint-stabilization-encapsulation',
    '/services/seattle/lead-paint-encapsulation-services':  '/services/seattle/lead-paint-stabilization-encapsulation',
    '/services/portland/lead-paint-inspection-services': '/services/portland/lead-paint-testing-inspection',
    '/services/seattle/lead-paint-inspection-services':  '/services/seattle/lead-paint-testing-inspection',
    '/services/portland/lead-paint-removal-for-historic-homes': '/services/portland/lead-paint-removal-surface-preparation',
    '/services/seattle/lead-paint-removal-for-historic-homes':  '/services/seattle/lead-paint-removal-surface-preparation',
    '/services/portland/lead-paint-safety-training-for-homeowners': '/services/portland/lead-paint-testing-inspection',
    '/services/seattle/lead-paint-safety-training-for-homeowners':  '/services/seattle/lead-paint-testing-inspection',
    '/services/portland/lead-paint-testing-in-portland': '/services/portland/lead-paint-testing-inspection',
    '/services/seattle/lead-paint-testing-in-portland':  '/services/seattle/lead-paint-testing-inspection',
    '/services/portland/lead-safety-training-for-homeowners': '/services/portland/lead-paint-testing-inspection',
    '/services/seattle/lead-safety-training-for-homeowners':  '/services/seattle/lead-paint-testing-inspection',
    '/services/portland/leadbased-paint-disposal-services': '/services/portland/lead-paint-containment-cleanup',
    '/services/seattle/leadbased-paint-disposal-services':  '/services/seattle/lead-paint-containment-cleanup',
    '/services/portland/leadbased-paint-testing-kits': '/services/portland/lead-paint-testing-inspection',
    '/services/seattle/leadbased-paint-testing-kits':  '/services/seattle/lead-paint-testing-inspection',
    '/services/portland/leadsafe-remodeling-consultations': '/services/portland/lead-safe-exterior-renovation',
    '/services/seattle/leadsafe-remodeling-consultations':  '/services/seattle/lead-safe-exterior-renovation',
    '/services/portland/leadsafe-remodeling-services': '/services/portland/lead-safe-exterior-renovation',
    '/services/seattle/leadsafe-remodeling-services':  '/services/seattle/lead-safe-exterior-renovation',
  },
});
