import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';
import sitemap from '@astrojs/sitemap';

export default defineConfig({
  site: 'https://crawlspacerot.com',
  integrations: [
    tailwind(),
    sitemap()
  ],
  output: 'static',
  redirects: {
    '/services/portland/crawlspace-access-door-installation': '/services/portland/crawlspace-access-entry',
    '/services/seattle/crawlspace-access-door-installation':  '/services/seattle/crawlspace-access-entry',
    '/services/portland/crawlspace-drainage-solutions': '/services/portland/crawlspace-moisture-vapor-waterproofing',
    '/services/seattle/crawlspace-drainage-solutions':  '/services/seattle/crawlspace-moisture-vapor-waterproofing',
    '/services/portland/crawlspace-energy-audit': '/services/portland/crawlspace-moisture-vapor-waterproofing',
    '/services/seattle/crawlspace-energy-audit':  '/services/seattle/crawlspace-moisture-vapor-waterproofing',
    '/services/portland/crawlspace-insulation-installation': '/services/portland/crawlspace-moisture-vapor-waterproofing',
    '/services/seattle/crawlspace-insulation-installation':  '/services/seattle/crawlspace-moisture-vapor-waterproofing',
    '/services/portland/crawlspace-moisture-barrier-installation': '/services/portland/crawlspace-moisture-vapor-waterproofing',
    '/services/seattle/crawlspace-moisture-barrier-installation':  '/services/seattle/crawlspace-moisture-vapor-waterproofing',
    '/services/portland/crawlspace-mold-remediation': '/services/portland/crawlspace-moisture-vapor-waterproofing',
    '/services/seattle/crawlspace-mold-remediation':  '/services/seattle/crawlspace-moisture-vapor-waterproofing',
    '/services/portland/crawlspace-pest-control-services': '/services/portland/crawlspace-moisture-vapor-waterproofing',
    '/services/seattle/crawlspace-pest-control-services':  '/services/seattle/crawlspace-moisture-vapor-waterproofing',
    '/services/portland/crawlspace-repair-and-maintenance': '/services/portland/crawlspace-structural-rot-dry-rot-repair',
    '/services/seattle/crawlspace-repair-and-maintenance':  '/services/seattle/crawlspace-structural-rot-dry-rot-repair',
    '/services/portland/crawlspace-structural-support-installation': '/services/portland/crawlspace-floor-system-framing-repair',
    '/services/seattle/crawlspace-structural-support-installation':  '/services/seattle/crawlspace-floor-system-framing-repair',
    '/services/portland/crawlspace-ventilation-improvement': '/services/portland/crawlspace-moisture-vapor-waterproofing',
    '/services/seattle/crawlspace-ventilation-improvement':  '/services/seattle/crawlspace-moisture-vapor-waterproofing',
    '/services/portland/crawl-space-access-door-installation': '/services/portland/crawlspace-access-entry',
    '/services/seattle/crawl-space-access-door-installation':  '/services/seattle/crawlspace-access-entry',
    '/services/portland/crawl-space-air-quality-improvement': '/services/portland/crawlspace-moisture-vapor-waterproofing',
    '/services/seattle/crawl-space-air-quality-improvement':  '/services/seattle/crawlspace-moisture-vapor-waterproofing',
    '/services/portland/crawl-space-cleanup-and-maintenance': '/services/portland/crawlspace-moisture-vapor-waterproofing',
    '/services/seattle/crawl-space-cleanup-and-maintenance':  '/services/seattle/crawlspace-moisture-vapor-waterproofing',
    '/services/portland/crawl-space-insulation-replacement': '/services/portland/crawlspace-moisture-vapor-waterproofing',
    '/services/seattle/crawl-space-insulation-replacement':  '/services/seattle/crawlspace-moisture-vapor-waterproofing',
    '/services/portland/crawl-space-moisture-barrier-installation': '/services/portland/crawlspace-moisture-vapor-waterproofing',
    '/services/seattle/crawl-space-moisture-barrier-installation':  '/services/seattle/crawlspace-moisture-vapor-waterproofing',
    '/services/portland/crawl-space-mold-remediation': '/services/portland/crawlspace-moisture-vapor-waterproofing',
    '/services/seattle/crawl-space-mold-remediation':  '/services/seattle/crawlspace-moisture-vapor-waterproofing',
    '/services/portland/crawl-space-rodent-and-pest-control': '/services/portland/crawlspace-moisture-vapor-waterproofing',
    '/services/seattle/crawl-space-rodent-and-pest-control':  '/services/seattle/crawlspace-moisture-vapor-waterproofing',
    '/services/portland/crawl-space-structural-repairs': '/services/portland/crawlspace-structural-rot-dry-rot-repair',
    '/services/seattle/crawl-space-structural-repairs':  '/services/seattle/crawlspace-structural-rot-dry-rot-repair',
    '/services/portland/crawl-space-ventilation-solutions': '/services/portland/crawlspace-moisture-vapor-waterproofing',
    '/services/seattle/crawl-space-ventilation-solutions':  '/services/seattle/crawlspace-moisture-vapor-waterproofing',
    '/services/portland/crawl-space-water-drainage-solutions': '/services/portland/crawlspace-moisture-vapor-waterproofing',
    '/services/seattle/crawl-space-water-drainage-solutions':  '/services/seattle/crawlspace-moisture-vapor-waterproofing',
  },
});
