import { SiteConfig } from './types';
import { getDBABySlug } from './dbas';

export const serviceConfigs: Record<string, SiteConfig> = {
  'deck-repair': {
    name: 'Deck Repair Experts',
    domain: getDBABySlug('deck-repair')?.domain || '',
    title: 'Portland Deck Repair Experts | Professional Deck Restoration',
    description: 'Expert deck repair and restoration services in Portland. Licensed, bonded, and insured. Free inspections and estimates.',
    primaryService: 'Deck Repair',
    serviceKeywords: ['deck repair', 'deck replacement', 'deck restoration', 'deck rot repair'],
    searchVolume: 33840,
    avgDifficulty: 31.44,
    avgCPC: 5.67,
    trafficShare: 24.1,
    phone: '(503) 885-0236',
    hubspotPortalId: '',
    hubspotFormId: '',
    googleAnalyticsId: 'G-Q9EZ1FYSNR'
  },
  'chimney-repair': {
    name: 'Chimney Repair Experts',
    domain: getDBABySlug('chimney-repair')?.domain || '',
    title: 'Portland Chimney Repair | Wood Chimney Framing & Rot Repair',
    description: 'Professional wood chimney repair and structural restoration in Portland. Specialized in chimney rot, framing, and waterproofing.',
    primaryService: 'Wood Chimney Repair',
    serviceKeywords: ['chimney repair', 'chimney rot', 'chimney framing', 'wood chimney repair'],
    searchVolume: 33330,
    avgDifficulty: 24.13,
    avgCPC: 8.80,
    trafficShare: 23.7,
    phone: '(503) 885-0236',
    hubspotPortalId: '',
    hubspotFormId: '',
    googleAnalyticsId: 'G-25W9Z2M4HM'
  },
  'siding-repair': {
    name: 'Siding Repair Experts',
    domain: getDBABySlug('siding-repair')?.domain || '',
    title: 'Portland Siding Repair & Replacement | Hardie Board Specialists',
    description: 'Professional siding repair and replacement in Portland. Experts in rot repair, Hardie board installation, and complete siding restoration.',
    primaryService: 'Siding Repair',
    serviceKeywords: ['siding repair', 'siding replacement', 'Hardie board', 'siding rot repair'],
    searchVolume: 32380,
    avgDifficulty: 25.63,
    avgCPC: 10.93,
    trafficShare: 23.1,
    phone: '(503) 885-0236',
    hubspotPortalId: '',
    hubspotFormId: '',
    googleAnalyticsId: 'G-D6C7VP5H03'
  },
  'crawlspace-rot': {
    name: 'Crawl Space Rot Repair',
    domain: getDBABySlug('crawlspace-rot')?.domain || '',
    title: 'Portland Crawl Space Rot Repair | Subfloor & Foundation Experts',
    description: 'Emergency crawl space rot repair and structural restoration. Subfloor repair, foundation wood replacement, moisture control.',
    primaryService: 'Crawl Space Rot Repair',
    serviceKeywords: ['crawl space rot', 'subfloor repair', 'foundation wood repair', 'crawl space restoration'],
    searchVolume: 18820,
    avgDifficulty: 17.00,
    avgCPC: 13.78,
    trafficShare: 13.4,
    phone: '(503) 885-0236',
    hubspotPortalId: '',
    hubspotFormId: '',
    googleAnalyticsId: 'G-7P220HY6SN'
  },
  'leak-repair': {
    name: 'Leak Repair Experts',
    domain: getDBABySlug('leak-repair')?.domain || '',
    title: 'Portland Leak Detection & Repair | Water Damage Prevention',
    description: 'Professional leak detection and repair services. Stop water damage before it starts with expert moisture intrusion solutions.',
    primaryService: 'Leak Repair',
    serviceKeywords: ['leak repair', 'leak detection', 'water damage repair', 'moisture intrusion'],
    searchVolume: 6780,
    avgDifficulty: 24.20,
    avgCPC: 14.62,
    trafficShare: 4.8,
    phone: '(503) 885-0236',
    hubspotPortalId: '',
    hubspotFormId: '',
    googleAnalyticsId: 'G-6EFXYCLWXM'
  },
  'lead-paint': {
    name: 'Lead Paint Services',
    domain: getDBABySlug('lead-paint')?.domain || '',
    title: 'Portland Lead Paint Removal | Certified Lead-Safe Renovation',
    description: 'Certified lead paint removal and lead-safe renovation services. Protecting families in historic Portland homes.',
    primaryService: 'Lead Paint Services',
    serviceKeywords: ['lead paint removal', 'lead safe renovation', 'lead testing', 'lead abatement'],
    searchVolume: 6070,
    avgDifficulty: 31.40,
    avgCPC: 2.37,
    trafficShare: 4.3,
    phone: '(503) 885-0236',
    hubspotPortalId: '',
    hubspotFormId: '',
    googleAnalyticsId: 'G-GFGVJQ899X'
  },
  'flashing-repair': {
    name: 'Flashing Repair Experts',
    domain: getDBABySlug('flashing-repair')?.domain || '',
    title: 'Portland Flashing Repair & Replacement | Waterproofing Specialists',
    description: 'Professional flashing repair and replacement services. Protect your home from water intrusion with expert installation.',
    primaryService: 'Flashing Repair',
    serviceKeywords: ['flashing repair', 'flashing replacement', 'window flashing', 'roof flashing'],
    searchVolume: 3250,
    avgDifficulty: 17.75,
    avgCPC: 8.95,
    trafficShare: 2.3,
    phone: '(503) 885-0236',
    hubspotPortalId: '',
    hubspotFormId: '',
    googleAnalyticsId: 'G-REEL7WTPD1'
  },
  'dry-rot': {
    name: 'Rot Repair Experts',
    domain: getDBABySlug('dry-rot')?.domain || '',
    title: 'Portland Rot Repair | Wood Rot & Dry Rot Specialists',
    description: 'Professional rot repair and wood rot remediation in Portland. Expert dry rot repair, moisture control, and structural restoration.',
    primaryService: 'Rot Repair',
    serviceKeywords: ['rot repair', 'dry rot repair', 'wood rot remediation', 'fungus treatment', 'rot removal'],
    searchVolume: 2570,
    avgDifficulty: 25.67,
    avgCPC: 3.38,
    trafficShare: 1.8,
    phone: '(503) 885-0236',
    hubspotPortalId: '',
    hubspotFormId: ''
  },
  'trim-repair': {
    name: 'Trim Repair Experts',
    domain: getDBABySlug('trim-repair')?.domain || '',
    title: 'Portland Trim Repair | Fascia, Soffit & Exterior Trim Restoration',
    description: 'Professional trim, fascia, and soffit repair services. Restore your home\'s exterior beauty and protection.',
    primaryService: 'Trim Repair',
    serviceKeywords: ['trim repair', 'fascia repair', 'soffit repair', 'exterior trim'],
    searchVolume: 1630,
    avgDifficulty: 21.33,
    avgCPC: 6.14,
    trafficShare: 1.2,
    phone: '(503) 885-0236',
    hubspotPortalId: '',
    hubspotFormId: '',
    googleAnalyticsId: 'G-5LCQ98B842'
  },
  'restoration': {
    name: 'Historic Restoration',
    domain: getDBABySlug('restoration')?.domain || '',
    title: 'Portland Historic Home Restoration | Period-Appropriate Repairs',
    description: 'Specialized historic home restoration services. Preserving Portland\'s architectural heritage with authentic, period-appropriate repairs.',
    primaryService: 'Historic Restoration',
    serviceKeywords: ['historic restoration', 'historic home repair', 'period restoration', 'heritage conservation'],
    searchVolume: 1330,
    avgDifficulty: 35.80,
    avgCPC: 7.73,
    trafficShare: 0.9,
    phone: '(503) 885-0236',
    hubspotPortalId: '',
    hubspotFormId: '',
    googleAnalyticsId: 'G-947760HMFH'
  },
  'beam-repair': {
    name: 'Beam Repair Experts',
    domain: getDBABySlug('beam-repair')?.domain || '',
    title: 'Portland Structural Beam Repair | Load-Bearing Beam Replacement',
    description: 'Professional structural beam repair and replacement. Expert load-bearing beam restoration and reinforcement.',
    primaryService: 'Beam Repair',
    serviceKeywords: ['beam repair', 'structural beam replacement', 'load bearing repair', 'beam restoration'],
    searchVolume: 440,
    avgDifficulty: 13.67,
    avgCPC: 7.02,
    trafficShare: 0.3,
    phone: '(503) 885-0236',
    hubspotPortalId: '',
    hubspotFormId: '',
    googleAnalyticsId: 'G-NB9Z98QEH5'
  }
};
