import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';
import sitemap from '@astrojs/sitemap';

export default defineConfig({
  site: 'https://rotrepairportland.com',
  integrations: [
    tailwind(),
    sitemap()
  ],
  output: 'static',
  redirects: {
    '/services/portland/comprehensive-dry-rot-assessments': '/services/portland/comprehensive-dry-rot-emergency-services',
    '/services/seattle/comprehensive-dry-rot-assessments':  '/services/seattle/comprehensive-dry-rot-emergency-services',
    '/services/portland/comprehensive-dry-rot-solutions': '/services/portland/comprehensive-dry-rot-emergency-services',
    '/services/seattle/comprehensive-dry-rot-solutions':  '/services/seattle/comprehensive-dry-rot-emergency-services',
    '/services/portland/crown-molding-and-trim-restoration': '/services/portland/exterior-siding-wall-rot-repair',
    '/services/seattle/crown-molding-and-trim-restoration':  '/services/seattle/exterior-siding-wall-rot-repair',
    '/services/portland/custom-wood-replacement': '/services/portland/comprehensive-dry-rot-emergency-services',
    '/services/seattle/custom-wood-replacement':  '/services/seattle/comprehensive-dry-rot-emergency-services',
    '/services/portland/deck-joist-dry-rot-inspection-and-repair': '/services/portland/deck-porch-balcony-rot-repair',
    '/services/seattle/deck-joist-dry-rot-inspection-and-repair':  '/services/seattle/deck-porch-balcony-rot-repair',
    '/services/portland/dry-rot-trim-replacement': '/services/portland/exterior-siding-wall-rot-repair',
    '/services/seattle/dry-rot-trim-replacement':  '/services/seattle/exterior-siding-wall-rot-repair',
    '/services/portland/emergency-dry-rot-repair': '/services/portland/comprehensive-dry-rot-emergency-services',
    '/services/seattle/emergency-dry-rot-repair':  '/services/seattle/comprehensive-dry-rot-emergency-services',
    '/services/portland/epoxy-reinforcement-for-rotted-wood': '/services/portland/comprehensive-dry-rot-emergency-services',
    '/services/seattle/epoxy-reinforcement-for-rotted-wood':  '/services/seattle/comprehensive-dry-rot-emergency-services',
    '/services/portland/epoxy-reinforcement-for-wood': '/services/portland/comprehensive-dry-rot-emergency-services',
    '/services/seattle/epoxy-reinforcement-for-wood':  '/services/seattle/comprehensive-dry-rot-emergency-services',
    '/services/portland/exterior-siding-repair-services': '/services/portland/exterior-siding-wall-rot-repair',
    '/services/seattle/exterior-siding-repair-services':  '/services/seattle/exterior-siding-wall-rot-repair',
    '/services/portland/exterior-trim-dry-rot-repair': '/services/portland/exterior-siding-wall-rot-repair',
    '/services/seattle/exterior-trim-dry-rot-repair':  '/services/seattle/exterior-siding-wall-rot-repair',
    '/services/portland/fascia-board-dry-rot-restoration': '/services/portland/roofline-overhang-rot-repair',
    '/services/seattle/fascia-board-dry-rot-restoration':  '/services/seattle/roofline-overhang-rot-repair',
    '/services/portland/foundation-and-framing-inspection': '/services/portland/structural-framing-rot-repair',
    '/services/seattle/foundation-and-framing-inspection':  '/services/seattle/structural-framing-rot-repair',
    '/services/portland/historic-home-dry-rot-repair': '/services/portland/comprehensive-dry-rot-emergency-services',
    '/services/seattle/historic-home-dry-rot-repair':  '/services/seattle/comprehensive-dry-rot-emergency-services',
    '/services/portland/porch-column-dry-rot-repair': '/services/portland/deck-porch-balcony-rot-repair',
    '/services/seattle/porch-column-dry-rot-repair':  '/services/seattle/deck-porch-balcony-rot-repair',
    '/services/portland/roof-eave-dry-rot-repair': '/services/portland/roofline-overhang-rot-repair',
    '/services/seattle/roof-eave-dry-rot-repair':  '/services/seattle/roofline-overhang-rot-repair',
    '/services/portland/rotten-trim-scarf-joint-repair': '/services/portland/exterior-siding-wall-rot-repair',
    '/services/seattle/rotten-trim-scarf-joint-repair':  '/services/seattle/exterior-siding-wall-rot-repair',
    '/services/portland/rotten-window-sill-repair': '/services/portland/window-door-rot-repair',
    '/services/seattle/rotten-window-sill-repair':  '/services/seattle/window-door-rot-repair',
    '/services/portland/seasonal-dry-rot-assessment': '/services/portland/comprehensive-dry-rot-emergency-services',
    '/services/seattle/seasonal-dry-rot-assessment':  '/services/seattle/comprehensive-dry-rot-emergency-services',
    '/services/portland/window-sill-dry-rot-replacement': '/services/portland/window-door-rot-repair',
    '/services/seattle/window-sill-dry-rot-replacement':  '/services/seattle/window-door-rot-repair',
  },
});
